#!/bin/bash

../bin/CastaliaBin $*

echo -e "\n\n\n===========================================================\n\nProduced with the following version of Castalia:"  >> SN-stats.sca

cat ../VERSION >> SN-stats.sca

echo -e "\n===========================================================\n\n\n***********************************************************\nSimulation's parameter settings were"  >> SN-stats.sca

cat ./omnetpp.ini | grep ^[^#]  >> SN-stats.sca

echo -e "\n----------------------------\nEnd of simulation\n---------------------------\n\n\n\n\n"  >> SN-stats.sca