#!/usr/bin/python
# ***************************************************************************************
# *  Copyright: National ICT Australia,  2007, 2008, 2009				*
# *  Developed at the Networks and Pervasive Computing program				*
# *  Author(s): Yuriy Tselishchev							*
# *  This file is distributed under the terms in the attached LICENSE file.		*
# *  If you do not find this file, copies can be found by writing to:			*
# *											*
# *      NICTA, Locked Bag 9013, Alexandria, NSW 1435, Australia			*
# *      Attention:  License Inquiry.							*
# *											*
# **************************************************************************************/

def read_file(name):
    f = open(name,"r")
    lines = f.readlines()
    f.close()

    for line in lines:
	line = line.strip()
	if (len(line) == 0 or line[0] == '#'): continue
	if (line.find("include") == 0):
	    file = line[8:]
	    pos = file.find(" #")
	    if (pos != -1): file = file[:pos]
	    read_file(file)
	else: print line
    
    return
    
read_file("omnetpp.ini")
